{
  description = "Rackctl — Linux control tools for the Tascam US-16x08 USB DSP mixer (CLI + GUI)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (pkgs) lib;

        # One source of truth for the version: the workspace manifest, the same
        # field `bump-version` stamps. No need to touch this file at release time.
        version = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).workspace.package.version;

        # Libraries eframe/winit/glow need. They are needed at build time (the
        # `-sys` crates link or probe them) and the GUI also dlopens several at
        # run time. The set mirrors the CI's apt packages:
        #   libasound2-dev   -> alsa-lib
        #   libgl1-mesa-dev  -> libGL
        #   libxkbcommon-dev -> libxkbcommon
        #   libwayland-dev   -> wayland
        #   libxcb*-dev      -> xorg.libxcb
        guiLibs = with pkgs; [
          libGL
          libxkbcommon
          wayland
          xorg.libxcb
          xorg.libX11
          xorg.libXcursor
          xorg.libXi
          xorg.libXrandr
        ];

        # The US-16x08 tools (both binaries). Further devices in the suite would
        # be packaged as sibling derivations here.
        us16x08 = pkgs.rustPlatform.buildRustPackage {
          pname = "rackctl-us16x08";
          inherit version;
          src = self;

          # Build against the committed lockfile — no network, reproducible.
          cargoLock.lockFile = ./Cargo.lock;

          nativeBuildInputs = [
            pkgs.pkg-config
            pkgs.makeWrapper
            pkgs.installShellFiles
          ];
          buildInputs = [ pkgs.alsa-lib ] ++ guiLibs;

          postInstall = ''
            # Shell completions, generated by the CLI itself (no card needed —
            # `completions` does not open a device).
            installShellCompletion --cmd rackctl-us16x08 \
              --bash <($out/bin/rackctl-us16x08 completions bash) \
              --fish <($out/bin/rackctl-us16x08 completions fish) \
              --zsh  <($out/bin/rackctl-us16x08 completions zsh)

            # Desktop entry for the GUI.
            install -Dm644 packaging/rackctl-us16x08-gui.desktop \
              $out/share/applications/rackctl-us16x08-gui.desktop

            # winit/glow load Wayland, GL and xkbcommon with dlopen at run time,
            # which does not consult the binary's RUNPATH — so put them on the
            # GUI's library path. The CLI only needs libasound, found via RUNPATH.
            wrapProgram $out/bin/rackctl-us16x08-gui \
              --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath guiLibs}
          '';

          meta = {
            description = "Rackctl control tools for the Tascam US-16x08 USB DSP mixer (CLI + GUI)";
            homepage = "https://github.com/malo-rte/rackctl";
            license = lib.licenses.mit;
            platforms = lib.platforms.linux;
            mainProgram = "rackctl-us16x08-gui";
          };
        };
      in
      {
        packages = {
          default = us16x08;
          rackctl-us16x08 = us16x08;
        };

        # `nix run .#rackctl-us16x08` (CLI) / `.#rackctl-us16x08-gui` (GUI);
        # bare `nix run` is the GUI.
        apps = {
          default = self.apps.${system}.rackctl-us16x08-gui;
          rackctl-us16x08-gui = {
            type = "app";
            program = "${us16x08}/bin/rackctl-us16x08-gui";
          };
          rackctl-us16x08 = {
            type = "app";
            program = "${us16x08}/bin/rackctl-us16x08";
          };
        };

        # `nix develop` — the build inputs plus the Rust toolchain and the gate's
        # tools. LD_LIBRARY_PATH lets a plain `cargo run -p rackctl-us16x08-gui`
        # find the GUI's runtime libraries.
        devShells.default = pkgs.mkShell {
          inputsFrom = [ us16x08 ];
          packages = with pkgs; [
            cargo
            rustc
            clippy
            rustfmt
            rust-analyzer
          ];
          LD_LIBRARY_PATH = lib.makeLibraryPath guiLibs;
        };
      }
    );
}
